openapi: 3.0.1
info:
  title: OpenWiFi User Portal
  description: API describing User Self Care interaction with OpenWifi.
  version: 1.0.0
  license:
    name: BSD3
    url: https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/LICENSE

servers:
  - url: 'https://localhost:16006/api/v1'

security:
  - bearerAuth: []
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            properties:
              ErrorCode:
                type: integer
              ErrorDetails:
                type: string
              ErrorDescription:
                type: string

    Unauthorized:
      description: The requested does not have sufficient rights to perform the operation.
      content:
        application/json:
          schema:
            properties:
              ErrorCode:
                type: integer
                enum:
                  - 0     # Success
                  - 1     # PASSWORD_CHANGE_REQUIRED,
                  - 2     # INVALID_CREDENTIALS,
                  - 3     # PASSWORD_ALREADY_USED,
                  - 4     # USERNAME_PENDING_VERIFICATION,
                  - 5     # PASSWORD_INVALID,
                  - 6     # INTERNAL_ERROR,
                  - 7     # ACCESS_DENIED,
                  - 8     # INVALID_TOKEN
              ErrorDetails:
                type: string
              ErrorDescription:
                type: string

    Success:
      description: The requested operation was performed.
      content:
        application/json:
          schema:
            properties:
              Operation:
                type: string
              Details:
                type: string
              Code:
                type: integer
    Error:
      description: The requested operation failed.
      content:
        application/json:
          schema:
            properties:
              Operation:
                type: string
              Details:
                type: string
              Code:
                type: integer
    BadRequest:
      description: The requested operation failed.
      content:
        application/json:
          schema:
            properties:
              Operation:
                type: string
              Details:
                type: string
              Code:
                type: integer

  schemas:
    HomeDeviceMode:
      type: object
      properties:
        type:
          type: string
          enum:
            - bridge
            - manual
            - nat
          default: automatic
        enableLEDS:
          type: boolean
          default: true
        subnet:
          type: string
          format: ipv4
        subnetMask:
          type: string
          format: ipv4
        startIP:
          type: string
          format: ipv4
        endIP:
          type: string
          format: ipv4
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64

    IPReservation:
      type: object
      properties:
        nickname:
          type: string
        ipAddress:
          type: string
          format: ipv4
        macAddress:
          type: string
          format: mac-address

    IPReservationList:
      type: object
      properties:
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
        reservations:
          type: array
          items:
            $ref: '#/components/schemas/IPReservation'

    DnsConfiguration:
      type: object
      properties:
        ISP:
          type: boolean
        custom:
          type: boolean
        primary:
          type: string
          format: ipv4
        seconfary:
          type: string
          format: ipv4

    InternetConnection:
      type: object
      properties:
        type:
          type: string
          enum:
            - manual
            - pppoe
            - automatic
        username:
          type: string
        password:
          type: string
        ipAddress:
          type: string
          format: ipv4
        subnetMask:
          type: string
          format: ipv4
        defaultGateway:
          type: string
          format: ipv4
        primaryDns:
          type: string
          format: ipv4
        secondaryDns:
          type: string
          format: ipv4
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64

    WifiNetwork:
      type: object
      properties:
        type:
          type: string
          enum:
            - main
            - guest
        name:
          type: string
        password:
          type: string
        encryption:
          type: string
        bands:
          type: array
          items:
            type: string
            enum:
              - 2G
              - 5G
              - 5GL
              - 5GU
              - 6G

    WifiNetworkList:
      type: object
      properties:
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
        networks:
          type: array
          items:
            $ref: '#/components/schemas/WifiNetwork'

    AccessTime:
      type: object
      properties:
        description:
          type: string
        day:
          type: string
        rangeList:
          type: array
          items:
            type: string

    AccessTimes:
      type: object
      properties:
        description:
          type: string
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/AccessTime'

    SubscriberDevice:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        macAddress:
          type: string
        manufacturer:
          type: string
        firstContact:
          type: integer
          format: int64
        lastContact:
          type: integer
          format: int64
        group:
          type: string
        icon:
          type: string
          format: uuid
        suspended:
          type: boolean
        ip:
          type: string
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
        schedule:
          $ref: '#/components/schemas/AccessTimes'

    SubscriberDeviceList:
      type: object
      properties:
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
        devices:
          type: array
          items:
            $ref: '#/components/schemas/SubscriberDevice'

    Association:
      type: object
      properties:
        name:
          type: string
        ssid:
          type: string
        macAddress:
          type: string
        rssi:
          type: integer
        power:
          type: integer
        ipv4:
          type: string
        ipv6:
          type: integer
        tx:
          type: integer
        rx:
          type: integer

    AssociationList:
      type: object
      properties:
        created:
          type: integer
          format: int64
        modified:
          type: integer
          format: int64
        associations:
          type: array
          items:
            $ref: '#/components/schemas/Association'

    Client:
      type: object
      properties:
        macAddress:
          type: string
        speed:
          type: string
        mode:
          type: string
        ipv4:
          type: string
        ipv6:
          type: integer
        tx:
          type: integer
        rx:
          type: integer

    ClientList:
      type: object
      properties:
        created:
          type: integer
          format: int64
          readOnly: true
        modified:
          type: integer
          format: int64
          readOnly: true
        clients:
          type: array
          items:
            $ref: '#/components/schemas/Client'

    Location:
      type: object
      properties:
        buildingName:
          type: string
        addressLines:
          type: array
          items:
            type: string
        city:
          type: string
        state:
          type: string
        postal:
          type: string
        country:
          type: string
        phones:
          type: array
          items:
            type: string
        mobiles:
          type: array
          items:
            type: string

    AccessPoint:
      type: object
      properties:
        id:
          type: string
          format: uuid
        macAddress:
          type: string
        name:
          type: string
        deviceType:
          type: string
        subscriberDevices:
          $ref: '#/components/schemas/SubscriberDeviceList'
        ipReservations:
          $ref: '#/components/schemas/IPReservationList'
        address:
          $ref: '#/components/schemas/Location'
        wifiNetworks:
          $ref: '#/components/schemas/WifiNetworkList'
        internetConnection:
          $ref: '#/components/schemas/InternetConnection'
        deviceMode:
          $ref: '#/components/schemas/HomeDeviceMode'
        dnsConfiguration:
          $ref: '#/components/schemas/DnsConfiguration'


    AccessPointList:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/AccessPoint'

    SubscriberInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        userId:
          type: string
          format: email
          readOnly: true
        firstName:
          type: string
        initials:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        secondaryEmail:
          type: string
          format: email
        accessPoints:
          $ref: '#/components/schemas/AccessPointList'
        serviceAddress:
          $ref: '#/components/schemas/Location'
        billingAddress:
          $ref: '#/components/schemas/Location'
        created:
          type: integer
          format: int64
          readOnly: true
        modified:
          type: integer
          format: int64
          readOnly: true

    PasswordChange:
      type: object
      properties:
        oldPassword:
          type: string
          format: password
        newPassword:
          type: string
          format: password

    PasswordCreation:
      type: object
      properties:
        newPassword:
          type: string
          format: password

    MFAChallengeRequest:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        question:
          type: string
        created:
          type: integer
          format: integer64
        method:
          type: string

    MFAChallengeResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        answer:
          type: string

    WebTokenRequest:
      description: User Id and password.
      type: object
      required:
        - userId
        - password
      properties:
        userId:
          type: string
          default: support@example.com
        password:
          type: string
          default: support
        newPassword:
          type: string
          default: support
        refreshToken:
          type: string
      example:
        userId: support@example.com
        password: support

    WebTokenResult:
      description: Login and Refresh Tokens to be used in subsequent API calls.
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
          format: int32
        idle_timeout:
          type: integer
          format: int32
        username:
          type: string
        created:
          type: integer
          format: int64
        userMustChangePassword:
          type: boolean
        errorCode:
          type: integer     # 0 = no error, 1 = passwordAlreadyUsed, 2=invalidPassword
        aclTemplate:
          $ref: '#/components/schemas/WebTokenAclTemplate'

    AclTemplate:
      type: object
      properties:
        Read:
          type: boolean
        ReadWrite:
          type: boolean
        ReadWriteCreate:
          type: boolean
        Delete:
          type: boolean
        PortalLogin:
          type: boolean

    WebTokenAclTemplate:
      type: object
      properties:
        aclTemplate:
          $ref: '#/components/schemas/AclTemplate'

    SubMfaConfig:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - disabled
            - sms
            - email
        email:
          type: string
          format: email
        sms:
          type: string

paths:
  /oauth2:
    post:
      tags:
        - Authentication
      summary: Get access token - to be used as Bearer token header for all other API requests.
      operationId: getAccessToken
      parameters:
        - in: query
          name: newPassword
          description: used when a user is trying to change her password. This will be the new password.
          schema:
            type: string
          required: false
        - in: query
          name: forgotPassword
          description: A user forgot her password. She needs to present her e-mail address in the userId and set this to true
          schema:
            type: boolean
          required: false
        - in: query
          name: requirements
          description: A user forgot her password. This will provided the password requirements.
          schema:
            type: boolean
          required: false
        - in: query
          name: resendMFACode
          schema:
            type: boolean
          required: false
        - in: query
          name: completeMFAChallenge
          schema:
            type: boolean
          required: false
      requestBody:
        description: User id and password
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/WebTokenRequest'
                - $ref: '#/components/schemas/MFAChallengeResponse'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/WebTokenResult'
                  - $ref: '#/components/schemas/MFAChallengeRequest'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'

  /oauth2/{token}:
    delete:
      tags:
        - Authentication
      summary: Revoke a token.
      operationId: removeAccessToken
      parameters:
        - in: path
          name: token
          schema:
            type:
              string
          required: true
      responses:
        204:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Success'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'

  /subscriber:
    get:
      tags:
        - Subscriber Information
      summary: Get the information about the subscriber
      operationId: getSubscriberInfo
      responses:
        200:
          $ref: '#/components/schemas/SubscriberInfo'
    put:
      tags:
        - Subscriber Information
      summary: Modify the information stored about the subscriber
      operationId: modifySubscriberInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriberInfo'
      responses:
        200:
          $ref: '#/components/schemas/SubscriberInfo'
        400:
          $ref: '#/components/responses/Error'

  /wiredClients:
    get:
      tags:
        - Clients
      summary: Get the list of wired clients
      operationId: getWiredClients
      parameters:
        - in: query
          name: deviceId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: Successfully retrieved client list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientList'

  /wifiClients:
    get:
      tags:
        - WiFi Clients
      summary: Get the list of wired clients
      operationId: getWifiClients
      parameters:
        - in: query
          name: deviceId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: Successfully retrieved client list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociationList'

  /submfa:
    get:
      tags:
        - MFA
      summary: Retrieve the current setting for MFA
      operationId: getMFS
      responses:
        200:
          $ref: '#/components/schemas/SubMfaConfig'

    put:
      tags:
        - MFA
      summary: Retrieve the current setting for MFA
      operationId: modifyMFS
      parameters:
        - in: query
          name: startValidation
          schema:
            type: boolean
          required: false
        - in: query
          name: completeValidation
          schema:
            type: boolean
          required: false
        - in: query
          name: challengeCode
          schema:
            type: string
          required: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubMfaConfig'
      responses:
        200:
          $ref: '#/components/schemas/SubMfaConfig'
        400:
          $ref: '#/components/responses/BadRequest'

  /action:
    post:
      tags:
        - Device Commands
      summary: Sending different commands to a device
      operationId: performAnAction
      parameters:
        - in: query
          name: action
          schema:
            type: string
            enum:
              - reboot
              - blink
              - upgrade
              - factory
              - refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mac:
                  type: string
                when:
                  type: integer
                  format: int64

      responses:
        200:
          $ref: '#/components/responses/Success'
        400:
          $ref: '#/components/responses/BadRequest'
